### ISSUE TITLE
AisView MVN Error

### ISSUE THREAD

**Issue by WSA-S** [dma-ais/AisView#1]
Maven  COMPILATION ERROR :

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /ais/devel/AisView/src/main/java/dk/dma/ais/view/rest/LegacyResource.java:[55,26] dk.dma.ais.tracker.TargetInfoToAisTarget is not public in dk.dma.ais.tracker; cannot be accessed from outside package
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.908s
[INFO] Finished at: Tue Apr 21 18:29:24 CEST 2015
[INFO] Final Memory: 28M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project ais-view: Compilation failure
[ERROR] /ais/devel/AisView/src/main/java/dk/dma/ais/view/rest/LegacyResource.java:[55,26] dk.dma.ais.tracker.TargetInfoToAisTarget is not public in dk.dma.ais.tracker; cannot be accessed from outside package
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by kaspernielsen** [comment]
@tbsalling can you take a look at this?

**Comment by tbsalling** [comment]
Yep. Will have a look.

**Comment by tbsalling** [comment]
Fixed now.

Problem was that AisStore and AisView were not migrated to TargetTracker after it was moved to targetTracker.TargetTracker in AisLib.

Build status is available here: https://dma.ci.cloudbees.com/
